require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'venus' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  target 'venusTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'venus-tvOS' do
  # Pods for venus-tvOS

  target 'venus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
